sudo: required
services:
  - docker

before_install:
  - docker build -t marcovergueira/docker-react -f Dockerfile.dev .

script:
  - docker run marcovergueira/docker-react npm run test -- --coverage
